name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Build & Release (Windows)
        if: runner.os == 'Windows'
        run: npm run package:win -- -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Release (macOS)
        if: runner.os == 'macOS'
        run: npm run package:mac -- -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Release (Linux)
        if: runner.os == 'Linux'
        run: npm run package:linux -- -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OctoBrowser-${{ runner.os }}
          path: |
            release/*.exe
            release/*.dmg
            release/*.AppImage
